version: "3.6"
services:
  web:
    image: craftcms/nginx:7.4-dev
    volumes:
      - .:/app
    env_file: .env
    ports:
      - "8080:8080"
    links:
      - "db:database"
    depends_on:
      - db
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: project
        MYSQL_USER: project
        MYSQL_PASSWORD: project
    volumes:
      - ./_temp/mysql:/var/lib/mysql